// Recovery integration tests.
//
// 1. Feeds the committed capture with dropped packets (tests/data/
//    recovery_dropped.bin, generated by feedgen --drop-rate 0.3) through the
//    GapTracker with a live RecoveryClient + in-test TCP retransmission
//    server serving the zero-drop capture (recovery_full.bin). Asserts every
//    gap is detected, all gaps heal, and the final book state is byte-
//    identical to replaying the zero-drop capture.
// 2. Feeds the zero-drop capture in a shuffled order (bounded displacement
//    inside the reorder window) and asserts packets are applied in sequence
//    order with a correct final book.

#include <gtest/gtest.h>

#include <arpa/inet.h>
#include <netinet/in.h>
#include <poll.h>
#include <sys/socket.h>
#include <unistd.h>

#include <atomic>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iterator>
#include <map>
#include <string>
#include <thread>
#include <vector>

#include "book_builder.hpp"
#include "decoder.hpp"
#include "gap_tracker.hpp"
#include "receiver.hpp"
#include "recovery_client.hpp"
#include "time_base.hpp"
#include "wiretap/itch.hpp"

namespace wt = wiretap;

namespace {

std::string data_file(const char* name) {
  return std::string(WIRETAP_TEST_DATA_DIR) + "/" + name;
}

std::vector<std::uint8_t> read_file(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  EXPECT_TRUE(f.good()) << "missing test data file: " << path;
  return std::vector<std::uint8_t>((std::istreambuf_iterator<char>(f)),
                                   std::istreambuf_iterator<char>());
}

struct Frame {
  std::uint64_t seq;
  std::vector<std::uint8_t> bytes;  // the whole packet
};

std::vector<Frame> walk_frames(const std::vector<std::uint8_t>& data) {
  std::vector<Frame> frames;
  std::size_t off = 0;
  while (off < data.size()) {
    std::size_t plen = 0;
    if (!wt::packet_length(data.data() + off, data.size() - off, plen)) {
      ADD_FAILURE() << "malformed capture at offset " << off;
      break;
    }
    Frame f;
    f.seq = wt::itch::be64(data.data() + off + wt::itch::kSessionLength);
    f.bytes.assign(data.begin() + static_cast<long>(off),
                   data.begin() + static_cast<long>(off + plen));
    frames.push_back(std::move(f));
    off += plen;
  }
  return frames;
}

// Returns [start,end] inclusive ranges of missing seqs, given the surviving
// seqs in order.
std::vector<std::pair<std::uint64_t, std::uint64_t>> holes(const std::vector<Frame>& frames) {
  std::vector<std::pair<std::uint64_t, std::uint64_t>> out;
  for (std::size_t i = 1; i < frames.size(); ++i) {
    if (frames[i].seq != frames[i - 1].seq + 1) {
      out.emplace_back(frames[i - 1].seq + 1, frames[i].seq - 1);
    }
  }
  return out;
}

// Minimal TCP retransmission server (same protocol as
// tools/retransmit_server.py): "GET <start> <end>\n" -> raw frames, close.
class TestRetransmitServer {
 public:
  explicit TestRetransmitServer(std::vector<std::uint8_t> capture)
      : data_(std::move(capture)), frames_(walk_frames(data_)) {
    for (const auto& f : frames_)
      index_[f.seq] = f;
  }

  bool start() {
    listen_fd_ = ::socket(AF_INET, SOCK_STREAM, 0);
    if (listen_fd_ < 0)
      return false;
    int yes = 1;
    ::setsockopt(listen_fd_, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof yes);
    struct sockaddr_in addr {};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    addr.sin_port = 0;
    if (::bind(listen_fd_, reinterpret_cast<struct sockaddr*>(&addr), sizeof addr) != 0) {
      ::close(listen_fd_);
      return false;
    }
    socklen_t alen = sizeof addr;
    ::getsockname(listen_fd_, reinterpret_cast<struct sockaddr*>(&addr), &alen);
    port_ = ntohs(addr.sin_port);
    if (::listen(listen_fd_, 4) != 0)
      return false;
    thread_ = std::thread([this] { run(); });
    return true;
  }

  std::uint16_t port() const { return port_; }

  void stop() {
    stop_ = true;
    if (thread_.joinable())
      thread_.join();
    if (listen_fd_ >= 0)
      ::close(listen_fd_);
  }

 private:
  void run() {
    while (!stop_) {
      struct pollfd pfd {};
      pfd.fd = listen_fd_;
      pfd.events = POLLIN;
      const int rc = ::poll(&pfd, 1, 50);
      if (rc <= 0)
        continue;
      const int fd = ::accept(listen_fd_, nullptr, nullptr);
      if (fd < 0)
        continue;
      handle(fd);
      ::close(fd);
    }
  }

  void handle(int fd) {
    std::string line;
    char ch;
    while (line.size() < 64) {
      const ssize_t r = ::recv(fd, &ch, 1, 0);
      if (r <= 0 || ch == '\n')
        break;
      line.push_back(ch);
    }
    std::uint64_t start = 0, end = 0;
    if (std::sscanf(line.c_str(), "GET %llu %llu", &start, &end) != 2 || end < start) {
      const std::string err = "ERROR bad request\n";
      ::send(fd, err.data(), err.size(), MSG_NOSIGNAL);
      return;
    }
    if (index_.find(start) == index_.end() || index_.find(end) == index_.end()) {
      const std::string err = "ERROR range unavailable\n";
      ::send(fd, err.data(), err.size(), MSG_NOSIGNAL);
      return;
    }
    for (std::uint64_t seq = start; seq <= end; ++seq) {
      const Frame& f = index_[seq];
      ::send(fd, f.bytes.data(), f.bytes.size(), MSG_NOSIGNAL);
    }
  }

  std::vector<std::uint8_t> data_;
  std::vector<Frame> frames_;
  std::map<std::uint64_t, Frame> index_;
  int listen_fd_ = -1;
  std::uint16_t port_ = 0;
  std::atomic<bool> stop_{false};
  std::thread thread_;
};

// Replays capture frames through (decoder + book) directly, in file order.
void replay_reference(const std::vector<Frame>& frames, wt::BookBuilder& book) {
  wt::Decoder dec;
  std::vector<wt::BookUpdate> updates;
  updates.reserve(256);
  for (const auto& f : frames) {
    updates.clear();
    const auto r = dec.decode_packet(f.bytes.data(), f.bytes.size(), updates);
    EXPECT_EQ(r.error, wt::DecodeError::Ok);
    for (const auto& u : updates)
      book.apply(u);
  }
}

void expect_same_books(const wt::BookBuilder& a, const wt::BookBuilder& b) {
  EXPECT_EQ(a.order_count(), b.order_count());
  EXPECT_EQ(a.symbol_count(), b.symbol_count());
  EXPECT_EQ(a.unknown_ref_events(), b.unknown_ref_events());
  for (int i = 0; i < 20; ++i) {
    char symbol[9];
    std::snprintf(symbol, sizeof symbol, "SYM%05d", i);
    wt::DepthSnapshot sa, sb;
    const bool fa = a.snapshot(symbol, 4096, sa);
    const bool fb = b.snapshot(symbol, 4096, sb);
    EXPECT_EQ(fa, fb) << symbol;
    ASSERT_EQ(sa.bids.size(), sb.bids.size()) << symbol << " bids";
    for (std::size_t j = 0; j < sa.bids.size(); ++j) {
      EXPECT_EQ(sa.bids[j].price_ticks, sb.bids[j].price_ticks) << symbol;
      EXPECT_EQ(sa.bids[j].qty, sb.bids[j].qty) << symbol;
    }
    ASSERT_EQ(sa.asks.size(), sb.asks.size()) << symbol << " asks";
    for (std::size_t j = 0; j < sa.asks.size(); ++j) {
      EXPECT_EQ(sa.asks[j].price_ticks, sb.asks[j].price_ticks) << symbol;
      EXPECT_EQ(sa.asks[j].qty, sb.asks[j].qty) << symbol;
    }
  }
}

}  // namespace

TEST(Recovery, RestoresBookByteIdenticalToZeroDropRun) {
  wt::TimeBase::instance().initialize();
  const auto full_data = read_file(data_file("recovery_full.bin"));
  const auto dropped_data = read_file(data_file("recovery_dropped.bin"));
  const std::vector<Frame> full = walk_frames(full_data);
  const std::vector<Frame> dropped = walk_frames(dropped_data);
  const auto expected_holes = holes(dropped);
  ASSERT_FALSE(expected_holes.empty()) << "fixture must contain dropped packets";

  // Sanity: the dropped capture is an exact subsequence of the full capture.
  std::map<std::uint64_t, bool> full_seqs;
  for (const auto& f : full)
    full_seqs[f.seq] = true;
  for (const auto& f : dropped)
    EXPECT_TRUE(full_seqs.count(f.seq)) << f.seq;
  std::uint64_t missing_total = 0;
  for (const auto& h : expected_holes)
    missing_total += h.second - h.first + 1;

  wt::BookBuilder reference;
  replay_reference(full, reference);

  TestRetransmitServer server(full_data);
  ASSERT_TRUE(server.start());

  wt::SpscRing<wt::GapRequest> gap_ring(64);
  wt::SpscRing<wt::Datagram> recovered_ring(1024);
  wt::RecoveryClient client("127.0.0.1", server.port());
  std::atomic<bool> stop{false};
  std::thread recovery_thread([&] { client.run(gap_ring, recovered_ring, stop); });

  wt::GapTracker tracker(/*window=*/1024, /*timeout_ns=*/10 * 1000000000ull);
  wt::BookBuilder book;
  wt::Decoder dec;
  std::vector<wt::BookUpdate> updates;
  updates.reserve(256);
  std::vector<std::uint64_t> applied_seq;

  auto apply_bytes = [&](const std::vector<std::uint8_t>& bytes, std::uint64_t seq) {
    updates.clear();
    const auto r = dec.decode_packet(bytes.data(), bytes.size(), updates);
    ASSERT_EQ(r.error, wt::DecodeError::Ok) << "seq " << seq;
    for (const auto& u : updates)
      book.apply(u);
    applied_seq.push_back(seq);
  };

  auto process = [&](const wt::Datagram& dg, bool recovered) {
    if (recovered)
      tracker.note_recovered_packet();
    const std::uint64_t seq = wt::itch::be64(dg.bytes.data() + wt::itch::kSessionLength);
    const std::uint64_t now = wt::TimeBase::instance().now_ticks();
    const auto res = tracker.push(seq, now, dg.bytes.data(), dg.length, now, now);
    if (res.disposition == wt::PacketDisposition::Apply) {
      apply_bytes(std::vector<std::uint8_t>(dg.bytes.data(), dg.bytes.data() + dg.length), seq);
    } else if (res.disposition == wt::PacketDisposition::Buffered && res.gap_detected) {
      ASSERT_TRUE(gap_ring.try_push(res.new_gap));
    }
    wt::BufferedPacket p;
    while (tracker.pop_applicable(p))
      apply_bytes(p.bytes, p.seq);
  };

  // Feed the surviving packets in file order, opportunistically draining the
  // recovered ring (the recovery thread runs concurrently).
  wt::Datagram dg;
  for (const auto& f : dropped) {
    dg = wt::Datagram{};
    dg.length = static_cast<std::uint32_t>(f.bytes.size());
    std::memcpy(dg.bytes.data(), f.bytes.data(), f.bytes.size());
    process(dg, false);
    while (recovered_ring.try_pop(dg))
      process(dg, true);
  }

  // Settle: let recovery finish; the tracker closes out once everything
  // heals.
  const auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(10);
  while (!tracker.settled() && std::chrono::steady_clock::now() < deadline) {
    while (recovered_ring.try_pop(dg))
      process(dg, true);
    tracker.advance_time(wt::TimeBase::instance().now_ticks());
    wt::BufferedPacket p;
    while (tracker.pop_applicable(p))
      apply_bytes(p.bytes, p.seq);
    std::this_thread::yield();
  }
  stop.store(true);
  recovery_thread.join();
  server.stop();

  // Every gap episode is detected, all heal, and the healed events cover
  // exactly the missing packets. (One episode may span several holes if the
  // live feed raced ahead of recovery.)
  const auto& events = tracker.events();
  ASSERT_FALSE(events.empty());
  EXPECT_LE(events.size(), expected_holes.size());
  std::uint64_t covered = 0;
  for (const auto& e : events) {
    EXPECT_TRUE(e.healed) << "gap " << e.start << "-" << e.end << " did not heal";
    covered += e.missing;
  }
  EXPECT_EQ(covered, missing_total);
  EXPECT_EQ(tracker.gaps_detected(), events.size());
  EXPECT_EQ(tracker.gaps_healed(), events.size());
  EXPECT_EQ(tracker.permanently_lost(), 0u);
  EXPECT_EQ(tracker.duplicates(), 0u);
  EXPECT_EQ(tracker.recovered_packets(), missing_total);
  EXPECT_EQ(tracker.expected_sequence(), full.back().seq + 1);
  EXPECT_TRUE(tracker.settled());
  EXPECT_EQ(client.errors(), 0u);
  EXPECT_EQ(client.packets_fetched(), missing_total);
  EXPECT_EQ(client.requests_served(), expected_holes.size());

  // Applied strictly in sequence order.
  for (std::size_t i = 1; i < applied_seq.size(); ++i) {
    EXPECT_EQ(applied_seq[i], applied_seq[i - 1] + 1);
  }
  EXPECT_EQ(applied_seq.size(), full.size());

  // Book byte-identical to the zero-drop replay.
  expect_same_books(book, reference);
}

TEST(Recovery, OutOfOrderArrivalWithinWindowAppliesInOrder) {
  wt::TimeBase::instance().initialize();
  const auto full_data = read_file(data_file("recovery_full.bin"));
  std::vector<Frame> frames = walk_frames(full_data);
  wt::BookBuilder reference;
  replay_reference(frames, reference);

  // Deterministic bounded shuffle: each packet moves at most 32 slots, well
  // inside the reorder window.
  std::uint32_t x = 0xDEADBEEFu;
  auto next = [&x]() {
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    return x;
  };
  const std::size_t n = frames.size();
  for (std::size_t i = 1; i + 1 < n; ++i) {  // keep seq 1 first
    const std::size_t j = i + next() % (std::min<std::size_t>(32, n - i));
    std::swap(frames[i], frames[j]);
  }

  wt::GapTracker tracker(/*window=*/1024, /*timeout_ns=*/60 * 1000000000ull);
  wt::BookBuilder book;
  wt::Decoder dec;
  std::vector<wt::BookUpdate> updates;
  updates.reserve(256);
  std::vector<std::uint64_t> applied_seq;

  auto apply_bytes = [&](const std::vector<std::uint8_t>& bytes, std::uint64_t seq) {
    updates.clear();
    const auto r = dec.decode_packet(bytes.data(), bytes.size(), updates);
    ASSERT_EQ(r.error, wt::DecodeError::Ok);
    for (const auto& u : updates)
      book.apply(u);
    applied_seq.push_back(seq);
  };

  for (const auto& f : frames) {
    const std::uint64_t now = wt::TimeBase::instance().now_ticks();
    const auto res = tracker.push(f.seq, now, f.bytes.data(), f.bytes.size(), now, now);
    EXPECT_NE(res.disposition, wt::PacketDisposition::Discard);
    if (res.disposition == wt::PacketDisposition::Apply) {
      apply_bytes(f.bytes, f.seq);
    }
    wt::BufferedPacket p;
    while (tracker.pop_applicable(p))
      apply_bytes(p.bytes, p.seq);
  }
  tracker.flush(wt::TimeBase::instance().now_ticks());
  wt::BufferedPacket p;
  while (tracker.pop_applicable(p))
    apply_bytes(p.bytes, p.seq);

  EXPECT_GT(tracker.gaps_detected(), 0u);                     // displaced packets did open gaps
  EXPECT_EQ(tracker.gaps_healed(), tracker.gaps_detected());  // all healed locally
  EXPECT_EQ(tracker.permanently_lost(), 0u);
  EXPECT_EQ(tracker.duplicates(), 0u);
  EXPECT_TRUE(tracker.settled());
  ASSERT_EQ(applied_seq.size(), frames.size());
  for (std::size_t i = 1; i < applied_seq.size(); ++i) {
    EXPECT_EQ(applied_seq[i], applied_seq[i - 1] + 1);  // strict seq order
  }
  expect_same_books(book, reference);
}
