#!/usr/bin/env python3
"""Replay a feedgen TSV manifest and dump the expected final book state.

Reference implementation for the C++ BookBuilder tests: applies the same
add/execute/cancel/delete/replace semantics to the manifest (which records
exactly what the generator wrote) and emits one row per live price level plus
an ORDERS summary row.

Output format:
  # WireTap book reference (generated by tools/bookref.py)
  SYMBOL\tB\tprice_ticks\tqty      (bids, best first)
  SYMBOL\tA\tprice_ticks\tqty      (asks, best first)
  ORDERS\t<open order count>
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict

MANIFEST_COLUMNS = ("seq", "type", "symbol", "side", "price", "qty", "ref",
                    "old_ref", "action", "ts")


def load_manifest(path):
    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            fields = line.rstrip("\n").split("\t")
            if len(fields) != len(MANIFEST_COLUMNS):
                raise SystemExit(
                    f"{path}: expected {len(MANIFEST_COLUMNS)} columns, got "
                    f"{len(fields)}: {line!r}")
            rows.append({
                "type": fields[1],
                "symbol": fields[2],
                "side": fields[3],
                "price": int(fields[4]),
                "qty": int(fields[5]),
                "ref": int(fields[6]),
                "old_ref": int(fields[7]),
            })
    return rows


def build(rows):
    orders = {}  # ref -> {"symbol", "side", "price", "qty"}
    bids = defaultdict(dict)
    asks = defaultdict(dict)
    unknown = 0

    def level_add(symbol, side, price, qty):
        table = bids if side == "B" else asks
        table[symbol][price] = table[symbol].get(price, 0) + qty

    def level_remove(symbol, side, price, qty):
        table = bids if side == "B" else asks
        if price not in table[symbol]:
            return
        q = min(qty, table[symbol][price])
        if q == 0:
            return
        table[symbol][price] -= q
        if table[symbol][price] == 0:
            del table[symbol][price]

    def reduce(order, qty):
        q = min(qty, order["qty"])
        level_remove(order["symbol"], order["side"], order["price"], q)
        order["qty"] -= q
        return order["qty"] == 0

    for row in rows:
        typ = row["type"]
        if typ in ("A", "F"):
            orders[row["ref"]] = dict(row)
            level_add(row["symbol"], row["side"], row["price"], row["qty"])
        elif typ in ("E", "X", "P"):
            order = orders.get(row["ref"])
            if order is None:
                unknown += 1
                continue
            if reduce(order, row["qty"]):
                del orders[row["ref"]]
        elif typ == "D":
            order = orders.get(row["ref"])
            if order is None:
                unknown += 1
                continue
            level_remove(order["symbol"], order["side"], order["price"],
                         order["qty"])
            del orders[row["ref"]]
        elif typ == "U":
            order = orders.get(row["old_ref"])
            if order is None:
                unknown += 1
                continue
            level_remove(order["symbol"], order["side"], order["price"],
                         order["qty"])
            del orders[row["old_ref"]]
            orders[row["ref"]] = {
                "symbol": order["symbol"],
                "side": order["side"],
                "price": row["price"],
                "qty": row["qty"],
            }
            level_add(order["symbol"], order["side"], row["price"],
                      row["qty"])
        # typ == "S": system events carry no book state

    return orders, bids, asks, unknown


def dump(orders, bids, asks, unknown, path):
    symbols = sorted(set(bids) | set(asks))
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("# WireTap book reference (generated by tools/bookref.py)\n")
        for sym in symbols:
            for price in sorted(bids.get(sym, {}), reverse=True):
                f.write(f"{sym}\tB\t{price}\t{bids[sym][price]}\n")
            for price in sorted(asks.get(sym, {})):
                f.write(f"{sym}\tA\t{price}\t{asks[sym][price]}\n")
        f.write(f"ORDERS\t{len(orders)}\n")
    if unknown:
        print(f"bookref: warning: {unknown} events referenced unknown orders",
              file=sys.stderr)


def main(argv=None):
    p = argparse.ArgumentParser(
        description="Dump the expected final book state for a feedgen manifest.")
    p.add_argument("--manifest", default="tests/data/roundtrip.tsv",
                   help="manifest TSV (default: %(default)s)")
    p.add_argument("--out", default="tests/data/book_expected.tsv",
                   help="output path (default: %(default)s)")
    args = p.parse_args(argv)

    rows = load_manifest(args.manifest)
    orders, bids, asks, unknown = build(rows)
    dump(orders, bids, asks, unknown, args.out)
    print(f"bookref: {len(rows)} events -> {len(orders)} open orders, "
          f"{sum(len(v) for v in bids.values()) + sum(len(v) for v in asks.values())} "
          f"levels, {unknown} unknown-ref events -> {args.out}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
